version: "3.9"

services:
  kwc-website:
    container_name: "kwc-website"
    image: ghcr.io/martokk/kwc-website:latest
    restart: unless-stopped
    volumes:
      # - /home/ubuntu/volumes/kwc-website/data:/kwc-website/data
      - ./app:/app
    ports:
      - "5000:5000"
