version: "3.9"

services:
  kwc_website:
    container_name: "kwc_website"
    image: ghcr.io/martokk/kwc_website:latest
    restart: unless-stopped
    volumes:
      # - /home/ubuntu/volumes/kwc_website/data:/kwc_website/data
      - ./app:/app
    ports:
      - "5000:5000"
