"""add_order_to_staff_and_board2

Revision ID: 0f663dcb48da
Revises: 26698ffdef74
Create Date: 2024-11-30 17:31:55.786510

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '0f663dcb48da'
down_revision = '26698ffdef74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
