"""added permissions 'programs' 'backup'

Revision ID: 1b9d062489c8
Revises: ab8c01f8bff0
Create Date: 2024-11-30 21:44:03.552661

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel  # added


# revision identifiers, used by Alembic.
revision = "1b9d062489c8"
down_revision = "ab8c01f8bff0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("userpermissions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("programs", sa.Boolean(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column("backup", sa.Boolean(), nullable=False, server_default="0"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("userpermissions", schema=None) as batch_op:
        batch_op.drop_column("backup")
        batch_op.drop_column("programs")

    # ### end Alembic commands ###
