"""add_order_to_staff_and_board

Revision ID: 26698ffdef74
Revises: 89195d799e68
Create Date: 2024-11-30 17:13:39.693968

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '26698ffdef74'
down_revision = '89195d799e68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_staff_order'), ['order'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_order'))
        batch_op.drop_column('order')

    # ### end Alembic commands ###
