"""add order field to partners

Revision ID: 754715e57d9e
Revises: 0f663dcb48da
Create Date: 2024-11-30 19:03:20.102274

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '754715e57d9e'
down_revision = '0f663dcb48da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
