"""kwc variables

Revision ID: 85b91e9e7c29
Revises: 08f04158143a
Create Date: 2024-12-01 18:58:02.114129

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel  # added


# revision identifiers, used by Alembic.
revision = "85b91e9e7c29"
down_revision = "08f04158143a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("variables", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "kwc_mission", sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=""
            )
        )
        batch_op.add_column(
            sa.Column(
                "kwc_vision", sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=""
            )
        )
        batch_op.add_column(
            sa.Column(
                "kwc_values", sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=""
            )
        )
        batch_op.drop_column("location")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("variables", schema=None) as batch_op:
        batch_op.add_column(sa.Column("location", sa.VARCHAR(), nullable=False))
        batch_op.drop_column("kwc_values")
        batch_op.drop_column("kwc_vision")
        batch_op.drop_column("kwc_mission")

    # ### end Alembic commands ###
