"""admin

Revision ID: 910ce6cb5ac4
Revises: 632585c44651
Create Date: 2024-11-29 21:40:30.911166

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '910ce6cb5ac4'
down_revision = '632585c44651'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
