"""add user permissions

Revision ID: ab8c01f8bff0
Revises: c6616d1b18b3
Create Date: 2024-11-30 19:50:07.987336

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'ab8c01f8bff0'
down_revision = 'c6616d1b18b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_index('ix_partners_order')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.create_index('ix_partners_order', ['order'], unique=False)

    # ### end Alembic commands ###
