"""contact_email

Revision ID: afa86353aeec
Revises: 85b91e9e7c29
Create Date: 2024-12-01 22:01:21.465548

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel  # added


# revision identifiers, used by Alembic.
revision = "afa86353aeec"
down_revision = "85b91e9e7c29"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contact_emails",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("subject", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("message", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sent", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("userpermissions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("contact_emails", sa.Boolean(), nullable=False, server_default="0")
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("userpermissions", schema=None) as batch_op:
        batch_op.drop_column("contact_emails")

    op.drop_table("contact_emails")
    # ### end Alembic commands ###
