"""add order field to partners

Revision ID: c6616d1b18b3
Revises: 754715e57d9e
Create Date: 2024-11-30 19:06:25.982189

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'c6616d1b18b3'
down_revision = '754715e57d9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=False))
        batch_op.alter_column('logo_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_partners_order'), ['order'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partners_order'))
        batch_op.alter_column('logo_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('order')

    # ### end Alembic commands ###
