"""updated faq

Revision ID: ccccf91500ed
Revises: e977c99c7011
Create Date: 2024-11-30 23:30:21.269626

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'ccccf91500ed'
down_revision = 'e977c99c7011'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
