"""edit wishlist

Revision ID: d5db4a9d9477
Revises: 0878fa3a1d87
Create Date: 2024-11-30 15:24:56.566672

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'd5db4a9d9477'
down_revision = '0878fa3a1d87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_wishlist')
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('wishlist')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wishlist', sa.VARCHAR(), nullable=False))
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.create_table('_alembic_tmp_wishlist',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_wishlist')
    )
    # ### end Alembic commands ###
